### ISSUE TITLE
Remove all.sh?

### ISSUE THREAD

**Issue by tobrun** [mapbox/mbgl-ci-images#30]
Are we still using `all.sh` in the root folder of this project? For Android it lists a couple of outdated configurations [here](https://github.com/mapbox/mbgl-ci-images/blob/master/all.sh#L46-L53). I believe this is a remains of an older configuration since everything is now done through circle-ci? 

cc @kkaefer

**Comment by kkaefer** [comment]
No we aren't

**Comment by tobrun** [comment]
thank you for confirming, removing this as part of ndk update in https://github.com/mapbox/mbgl-ci-images/pull/29.
