### ISSUE TITLE
Add more python packages 

### ISSUE THREAD

**Issue by tobrun** [mapbox/mbgl-ci-images#38]
For CI work in mobile metrics, I'm currently installing the following python libraries:

>    pip install requests
      pip install gitpython
      pip install future

**Comment by LukasPaczos** [comment]
We should also use Python 3 in the Android base image.

**Comment by tobrun** [comment]
Now with working more with python, we should do this differently. We need to add requirements.txt files that acts as dependency files for pip. We should cache these dependencies as we do for other build systems (eg. gradle).
