### ISSUE TITLE
Accept Android SDK licenses

### ISSUE THREAD

**Issue by tobrun** [mapbox/mbgl-ci-images#7]
Hitting following on CI when trying to run a newer project on an image found in this repo. 

```java
Checking the license for package Android SDK Build-Tools 25.0.3 in /android/sdk/licenses
Warning: License for package Android SDK Build-Tools 25.0.3 not accepted.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> You have not accepted the license agreements of the following SDK components:
  [Android SDK Build-Tools 25.0.3].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

BUILD FAILED
```

25.0.3 is the latest stable build tool and we need to update the configuration [here](https://github.com/mapbox/mbgl-ci-images/blob/master/android-ndk-r15/Dockerfile#L19). Would love to look into a solution that would work for any SDK build tools version though not sure if that is possible.

**Comment by tobrun** [comment]
Reverted to 25.0.2 for this specific project but now hitting:

```
You have not accepted the license agreements of the following SDK components:
  [ConstraintLayout for Android 1.0.2, Solver for ConstraintLayout 1.0.2].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
```

Updating the title to `Accept Android SDK licenses`

**Comment by zugaldia** [comment]
> Reverted to 25.0.2 for this specific project but now hitting:

In case it helps, I've fixed that error in the past adding the following two lines to the `pre` section of the `circle.yml` file:

```
- echo y | android update sdk --no-ui --all --filter "tool,extra-android-m2repository,extra-android-support,extra-google-google_play_services,extra-google-m2repository"
- echo y | $ANDROID_HOME/tools/bin/sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
```

**Comment by tobrun** [comment]
I was aiming at extending the solution we already have for accepting licenses [here](https://github.com/mapbox/mbgl-ci-images/blob/master/android-ndk-r15/Dockerfile#L19). This was based on a Jake Wharton solution, more info on that [here](https://stackoverflow.com/a/38381577/1281750). I'm guessing that we are missing the extra preview line there that incorporates the constrain layout (even though it's out of alpha and a stable version is available).

**Comment by zugaldia** [comment]
> This was based on a Jake Wharton solution

I don't know who that is but I hope you know what you're doing picking his way over mine.

**Comment by tobrun** [comment]
Been looking at the circleci-images and how they are doing it:
https://github.com/circleci/circleci-images/blob/master/android/Dockerfile.m4#L34

Maybe we should look into adding the same configuration? 
Circle-ci will keep maintaining the linked file with future platform updates.
This will make our maintenance in the future more easy.

cc @kkaefer

**Comment by tobrun** [comment]
Updating images in https://github.com/mapbox/mbgl-ci-images/pull/10
